### DISCUSSION TITLE
Referencing variable from a file in a template

### DISCUSSION THREAD

**Discussion by alexlykasov** [takomo-io/takomo#169] [Q&A] [answered]
Hi guys! According to Takomo documentation, or at least as I understood it, we can load variables from a file by specifying `--var-file name=FILE` argument for the `takomo deploy` command.
I have variables.yml file with this content
```
buckets:
  - bucketName: bucket1
    expirationDays: 30
  - bucketName: bucket2
    expirationDays: 60
```
I have a template where I want to iterate over the `buckets` list like this:
```
  {{#each var.buckets}}
  Bucket{{bucketName}}:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: {{bucketName}}
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: {{expirationDays}}
            Status: Enabled
  {{/each}}
```
And when I try deploying the stack `npx tkm stacks deploy -y /mystack --var-file variables.yml`, I'm getting the following error:
`Template format error: YAML not well-formed.`

Can you provide an example how to do such a thing in a correct way?

**Comment by hmeltaus** [comment, marked as answer]
Hi, you don't have Resources block in your template. Did you intentionally leave it out from the snippet?

I was able to make it work using this template file:

```
Resources:
  {{#each var.buckets}}
  Bucket{{bucketName}}:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: {{bucketName}}
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: {{expirationDays}}
            Status: Enabled
  {{/each}}
```

You can also adjust the logging level with `--log debug` or `--log trace` options to get more information on what actually happens. When using the trace logging level you can see the rendered template files which might help to spot the error.  

What Takomo version you are using?
