### ISSUE TITLE
Immutable parameters

### ISSUE THREAD

**Issue by hmeltaus** [takomo-io/takomo#120]
Sometimes stack parameters are used to create resources that should not be updated afterward because updating requires replacing the resource. 

We can prevent this by marking the stack parameter as immutable in the stack configuration file. One caveat though, it's not possible to know the current parameter value for `noEcho` parameters.

**Example: Marking a static parameter as immutable**

Before:

```
parameters:
  MyParam: 1234
```

After:

```
parameters:
  MyParam:
    value: 1234
    immutable: true
```

**Example: Marking a resolver parameter as immutable**

Before:

```
parameters:
  MyParam:
    resolver: stack-output
    stack: /stack1.yml
    output: OutputName
```

After:

```
parameters:
  MyParam:
    resolver: stack-output
    stack: /stack1.yml
    output: OutputName
    immutable: true
```
