### ISSUE TITLE
Command resolver throws a validation error on "confidential" property

### ISSUE THREAD

**Issue by mfonsen** [takomo-io/takomo#122]
According to https://takomo.io/docs/stacks/parameter-resolvers/#command command resolver supports confidential property. However using it results in validation error. There is no example so maybe my configuration is wrong?

Takomo version: 2.11.0

Stack configuration:
```
template: a.yml
depends: ...
hooks: ...
parameters:
  ...
  SecretParam:
    resolver: cmd
    command: foo
    confidential: true

```
Relevant log output:

```
 2020-10-20 11:20:22 +0300 [debug] - Init resolver 'cmd' for parameter 'SecretParam' with properties: <concealed>

ERROR
-----
1 validation error(s) in parameter 'SecretParam' of stack config file /app/aws/stacks/events/eu-west-1/a.yml:

  - "confidential" is not allowed


OTHER INFO
----------
Your environment:
  OS:              darwin
  Node version:    v14.14.0
  Takomo version:  2.11.0

Get support:
  Docs:  https://takomo.io
  Bugs:  https://github.com/takomo-io/takomo/issues

```
