### ISSUE TITLE
Expose tags to Handlebar as an array instead of object

### ISSUE THREAD

**Issue by hmeltaus** [takomo-io/takomo#129]
Current tags are exposed as an object to configuration files and stack templates like so:

```
tags:
  Tag1Name: tag1Value
  Tag2Name: tag2Value
``` 

This makes them harder to use in Handlebars. Let's expose tags as an array like so:

```
tags:
  - key: Tag1Name
    value: tag1Value
  - key: Tag2Name
    value: tag2Value
```
