### ISSUE TITLE
Load deployment targets from an external repository

### ISSUE THREAD

**Issue by hmeltaus** [takomo-io/takomo#172]
Add support to load deployment targets from external repositories. The repository could be a filesystem, dynamodb etc. 

Implement support for built-in filesystem repository. 

User enables loading of targets from an external repository by specifying the repository type and repository-type-specific configuration in takomo.yml file. For example:

```
deploymentTargets:
  repository:
    type: filesystem
    dir: targets
```
