### ISSUE TITLE
Add option to expose stack AWS credentials to cmd hook

### ISSUE THREAD

**Issue by hmeltaus** [takomo-io/takomo#177]
Add option to expose stack AWS crendentials as environment variables to cmd hook.

The configuration should look like this:

```
hooks:
  - name: hook-name
    type: cmd
    command: ls -la
    exposeStackCredentials: true
```
