### ISSUE TITLE
Add support to specify validation schemas for stack configuration

### ISSUE THREAD

**Issue by hmeltaus** [takomo-io/takomo#186]
It's already possible to provide custom Joi validation schemas. Let's make it possible to specify schemas for different stack properties, e.g. 
- name
- tags
- parameters
- data

The configuration could look like this:

```
schemas:
  name: <schemas used to validate stack name>
  tags: <schemas used to validate stack tags>
  parameters: <schemas used to validate stack parameters>
  data: <schemas used to validate stack data>
```

It should be possible to specify zero, one or more schemas per property. It should be possible to define schemas in stack group and stack configuration. Stacks could append more schemas to the ones they inherit from their parent.
