### ISSUE TITLE
Keep data type for tag values during the schema validation

### ISSUE THREAD

**Issue by kallesoranko** [takomo-io/takomo#360]
Tag values are automatically converted to strings before validation. It would be useful to retain the data type for the tag values during the validation and convert the type when sending the request to the API for tag creation.

Below is an example of a log trace when creating a stack. `cost-center` tag value is an integer type in stack definition file but converted to a string.

```yaml
tags:
  - key: environment
    value: dev
  - key: cost-center
    value: '1234'
```

Takomo version: 4.1.0
