### ISSUE TITLE
Takomo fails to create cascading OUs when SCPs are being used.

### ISSUE THREAD

**Issue by stenla-ws** [takomo-io/takomo#45]
```yaml

masterAccountId: "XXXYYYZZZ"

trustedAwsServices:
  - cloudtrail.amazonaws.com
  - config.amazonaws.com
  - ram.amazonaws.com
  - sso.amazonaws.com

serviceControlPolicies:
  FullAWSAccess:
    description: AWS managed default policy
    awsManaged: true
  AllowedRegions:
    description: Set allowed regions

organizationalUnits:
  
  Root:
    serviceControlPolicies:
      - FullAWSAccess
    accounts:
      - "XXXYYYZZZ" #master
      - "ZZZYYYXXX" #shared
      - "YYYXXXZZZ" #bc

  Root/WebProject:
    serviceControlPolicies:
      - FullAWSAccess
      - AllowedRegions
  Root/WebProject/Development:
    accounts:
      - "TTTRRRZZZ" #dev
  Root/WebProject/Production:
    accounts:
      - "ZZZRRRTTT" #prd
```

Expection: Takomo creates OUs WebProject, WebProject/Development and WebProject/Production, adds dev and prd account to OUs and attachs SCPs.

Reality: Takomo fails, saying dev account ID is defined more than once.

Output:
```yaml
lsten:takomo lauri$ takomo org deploy

ERROR
-----
Account TTTRRRZZZ is defined more than once


Your environment:
  OS:              darwin
  Node version:    v10.7.0
  Takomo version:  1.2.1

Get support:
  Docs:  https://takomo.io
  Bugs:  https://github.com/takomo-io/takomo/issues

```
