### ISSUE TITLE
Expose stack object to stack configuration files

### ISSUE THREAD

**Issue by hmeltaus** [takomo-io/takomo#81]
Let's expose the current stack object in stack configuration files. 

The stack object should have the following properties:
- path = the stack path without region
- pathSegments = the stack path without region split into an array using `/` as a separator
- configFile.filePath = relative path to stack configuration file
- configFile.basename = stack configuration file name
- configFile.name = stack configuration file name without the file extension
- configFile.dirPath = relative path to directory where the stack configuration file is located

**Example**

If we have a stack with a stack path `/dev/eu-west-1/example/stax.yml` the stack object would look like this:

```
path: /dev/eu-west-1/example/stax.yml
pathSegments:
  - dev
  - eu-west-1
  - example
  - stax.yml
configFile:
  filePath: dev/eu-west-1/example/stax.yml
  basename: stax.yml
  name: stax
  dirPath: dev/eu-west-1/example
```

You could then use the stack object in a stack configuration files like so:

```
data:
  message: The stack path is {{ stack.path }}
```
